
SELECT 
	'agsolutic_aps2024' as db,
    t.doc_id,
    t.familia_id,
    t.tipodocumento ,
    t.primerapellido ,
    t.segundoapellido ,
    t.primernombre ,
    t.segundonombre ,
    t.gestacion ,
    t.condicioncronica,
    t.esquemavacunacion,
    t.desparasitacion ,
    t.valoracion,
    t.higiene_oral,
    t.aseguradora ,
    t.regimen ,
    t.metodosanticonceptivos,
    t.infeccionestransmisionsexual,
    t.controlP,
    t.consumospa,
    t.tomacitologia,
    t.mamografia,
    t.remisionespecifica,
    t.discapacidad,
    t.canalizacionuno , 
    t.canalizaciondos ,
    t.canalizaciontres ,
    s.id,
    t.cursodevida,
    s.fecha,
    s.apellidosfamilia,
    u.microterritorio,
    u.cod_microterritorio,
    u.comuna,
    u.territorio,
    u.zona,
    CASE 
        WHEN t.familia_id IS NULL THEN 'SIN_FAMILIA_ID'
        WHEN f.id IS NULL THEN 'ID_FAMILIA_INVALIDO'
        WHEN COUNT(*) OVER (PARTITION BY t.doc_id) = 1 THEN 'UNICO_Y_VALIDO'
        ELSE 'DUPLICADO'
    END AS estado
FROM (
    SELECT 
    numerodoc AS doc_id ,
    familia_id, 
    tipodocumento , 
    primerapellido , 
    segundoapellido , 
    primernombre , 
    segundonombre,
    gestacion ,
    condicioncronica,
    esquemavacunacion,
    desparasitacion ,
    valoracionmedica as valoracion,
    saludoral as higiene_oral,
    aseguradora ,
    regimen ,
    metodosanticonceptivos,
    infeccionestransmisionsexual,
    controlprenatal as controlP,
    consumospa,
    tomacitologia,
    mamografia,
    remisionespecifica,
    discapacidad,
    canalizacionuno ,
    canalizaciondos ,
    canalizaciontres ,
    'Adulto' as cursodevida 
    FROM agsolutic_aps2024.juventudadultos
    UNION ALL
    SELECT 
    numerodoc AS doc_id ,
    familia_id, 
    tipodocumento , 
    primerapellido , 
    segundoapellido , 
    primernombre , 
    segundonombre,
    gestacion ,
    condicioncronica,
    esquemavacunacion,
    desparasitacion ,
    valoracionmedica as valoracion,
    saludoral as higiene_oral,
    aseguradora ,
    regimen ,
    metodosanticonceptivos,
    infeccionestransmisionsexual,
    controlprenatal as controlP,
    consumospa,
    tomacitologia,
    mamografia,
    remisionespecifica,
    discapacidad,
    canalizacionuno ,
    canalizaciondos ,
    canalizaciontres ,
    'Infante' as cursodevida FROM agsolutic_aps2024.infantils
    UNION ALL
    SELECT 
    numerodoc AS doc_id ,
    familia_id, 
    tipodocumento , 
    primerapellido , 
    segundoapellido , 
    primernombre , 
    segundonombre,
    gestacion ,
    condicioncronica,
    esquemavacunacion,
    desparasitacion ,
    valoracionmedica as valoracion,
    saludoral as higiene_oral,
    aseguradora ,
    regimen ,
    metodosanticonceptivos,
    infeccionestransmisionsexual,
    controlprenatal as controlP,
    consumospa,
    tomacitologia,
    mamografia,
    remisionespecifica,
    discapacidad,
    canalizacionuno ,
    canalizaciondos ,
    canalizaciontres ,
    'PrimeraInfancia' as cursodevida FROM agsolutic_aps2024.primerainfancias
    UNION ALL
    SELECT     
    numerodoc AS doc_id ,
    familia_id, 
    tipodocumento , 
    primerapellido , 
    segundoapellido , 
    primernombre , 
    segundonombre,
    gestacion ,
    condicioncronica,
    esquemavacunacion,
    desparasitacion ,
    valoracionmedica as valoracion,
    saludoral as higiene_oral,
    aseguradora ,
    regimen ,
    metodosanticonceptivos,
    infeccionestransmisionsexual,
    controlprenatal as controlP,
    consumospa,
    tomacitologia,
    mamografia,
    remisionespecifica,
    discapacidad,
    canalizacionuno ,
    canalizaciondos ,
    canalizaciontres ,
    'Adolescencia' as cursodevida FROM agsolutic_aps2024.adolescencias
) t
LEFT JOIN agsolutic_aps2024.familias f ON f.id = t.familia_id
LEFT JOIN agsolutic_aps2024.sociambientals s ON f.sociambiental_id = s.id 
LEFT JOIN agsolutic_aps2024.ubicaciones u ON s.ubicacion_id = u.id